In [5]:
import tensorflow as tf

#Indexing and expanding the tensors.
#Tensors can be indexed just like python list.

#create rank4 tensor.

rank4_tensor = tf.zeros(shape=(2,3,4,5))
print(rank4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [4]:
#get the first two element of each dimension

rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [8]:
#get the first element of each dimension except the final .

print(rank4_tensor[:1, :1, :1 ]) #or
print(rank4_tensor[:1,:1,:1,:])

tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)
tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [9]:
#create a rank2 tensor .
#rank2 tensor means tensor with 2 dimenson.

rank2_tensor = tf.constant([[2,3],
                            [4,5]])
print(rank2_tensor)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [10]:
print(rank2_tensor.shape)
print(rank2_tensor.ndim)

(2, 2)
2


In [11]:
#get the last item of each row from rank2 tensor.

rank2_tensor[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]], dtype=int32)>

In [17]:
#add extra dimension to rank2 tensor

rank3_tensor = rank2_tensor[:,:,tf.newaxis]
print(rank3_tensor) #or


tf.Tensor(
[[[2]
  [3]]

 [[4]
  [5]]], shape=(2, 2, 1), dtype=int32)


In [18]:
rank3_tensor = rank2_tensor[...,tf.newaxis]
print(rank3_tensor)

tf.Tensor(
[[[2]
  [3]]

 [[4]
  [5]]], shape=(2, 2, 1), dtype=int32)


In [20]:
#Alternative
tf.expand_dims(rank2_tensor, axis = -1) # -1 means expanding the final axi

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [21]:
tf.expand_dims(rank2_tensor, axis = 0) #expanding the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]]], dtype=int32)>

In [22]:
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [23]:
tf.expand_dims(rank2_tensor, axis = 1) #expanding the 1-axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 3]],

       [[4, 5]]], dtype=int32)>

In [1]:
#Here the number will be same in the tensor , only the dimension changes.

In [2]:
#Manipulating tensors (tensor operation)
#Basic operation are : +, -, *, /

import tensorflow as tf

In [4]:
tensor = tf.constant([[10,7],
                      [3,4]])
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [5]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [6]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [7]:
tensor - 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10, -13],
       [-17, -16]], dtype=int32)>

In [8]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [9]:
#We can use tensorflow built in function instead of above direct mathematic 
#sign because using tensorfolw builtin function results in faster operation.

In [10]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [11]:
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [12]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [13]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>