Changing the data types of tensors.

Finding the min, max, mean, variance and standard devation.

Finding the positional minimum and positional maximum.

In [2]:
import tensorflow as tf

In [3]:
#changing the data type of tensors.

#create  new tensor.

B = tf.constant([1.7, 7.4])
C = tf.constant([7, 10])

print(B.dtype)
print(C.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


In [4]:
#change the data type from float32 to float16. (Mixed precision)

D = tf.cast(B, dtype = tf.float16)
D.dtype

tf.float16

In [5]:
E = tf.cast(C, dtype = tf.float16)
E.dtype

tf.float16

Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory.

In [6]:
#Tensor aggregation : condesing tesor from multiple values 
#down to a smaller amount of values. (min, max, mean, sum, variance, std)

data = tf.constant([-1, -2])
print(data)
print(tf.abs(data))

tf.Tensor([-1 -2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [10]:
#create a random tensor with values b/w 0 and 100 of size 50.
import numpy as np
random_tensor = tf.constant(np.random.randint(0,10, size = 50))
print(random_tensor)

tf.Tensor(
[8 4 3 6 5 8 4 8 6 5 7 5 8 1 9 9 3 4 4 4 3 0 6 9 7 2 6 2 9 4 6 5 2 8 0 3 4
 4 0 9 3 8 8 0 4 3 4 6 3 7], shape=(50,), dtype=int64)


In [11]:
print(tf.size(random_tensor))
print(random_tensor.shape)
print(random_tensor.ndim)

tf.Tensor(50, shape=(), dtype=int32)
(50,)
1


In [13]:
#find the minimum, maximum, mean and sum of random_tensor

print('minimum:', tf.reduce_min(random_tensor))
print('maximum:', tf.reduce_max(random_tensor))
print('mean:', tf.reduce_mean(random_tensor))
print('sum:',tf.reduce_sum(random_tensor))

minimum: tf.Tensor(0, shape=(), dtype=int64)
maximum: tf.Tensor(9, shape=(), dtype=int64)
mean: tf.Tensor(4, shape=(), dtype=int64)
sum: tf.Tensor(246, shape=(), dtype=int64)


In [15]:
#find the variance

tf.math.reduce_variance(tf.cast(random_tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=6.833599>

In [16]:
#find the standard deviation

tf.math.reduce_std(tf.cast(random_tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.6141152>

In [22]:
#create a new tensor for finding positional minimum and maximum.
tf.random.set_seed(42)
new_tensor = tf.random.uniform(shape = [50])
print(new_tensor)

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)


In [24]:
#find the positional argument

tf.argmax(new_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [25]:
#Index on our largest value position.

new_tensor[tf.argmax(new_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [26]:
#find the maximum value of new_tensor.

tf.reduce_max(new_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [27]:
#check for equality

new_tensor[tf.argmax(new_tensor)] == tf.reduce_max(new_tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [28]:
#find the positional minimum

tf.argmin(new_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [29]:
#Find the minimum using positional minimum index

new_tensor[tf.argmin(new_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>