In [1]:
#Squeezing a tensor (removing all 1-dimensions axes).

import tensorflow as tf

In [8]:
#create a tensor

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape= [50]), shape = (1,1,1,1,50))
print(G)
print('\n')
print(G.shape)

tf.Tensor(
[[[[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
     0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
     0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
     0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
     0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
     0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
     0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
     0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
     0.7381023  0.32054043]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)


(1, 1, 1, 1, 50)


In [10]:
G_squeezed = tf.squeeze(G)
print(G_squeezed)
print(G_squeezed.shape)

#Note: Squeeze removes dimension of size 1 from the tensor.

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)
(50,)


In [11]:
#One- Hot encoing tensors

#create a list of indices.

some_list = [0,1,2,3]
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [12]:
#Specify custom values for one hot encoding.

tf.one_hot(some_list, depth = 4, on_value = "yo I love deep learning", off_value = "I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [13]:
#Trying out more tensor math operaions. squaring, log, square root.

#create a new tensor.

H = tf.range(1, 10)
print(H)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [14]:
#square it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [15]:
#Square root
tf.sqrt(H)

InvalidArgumentError: ignored

In [16]:
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142137, 1.7320509, 2.       , 2.2360682, 2.4494898,
       2.6457515, 2.8284273, 3.0000002], dtype=float32)>

In [17]:
#Find the log

tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Exploring tensor and numpy compatibility.

Tensors interact beautifully with numpy arrays.

In [19]:
#create a tensor directly from numpy array.

import numpy as np
J = tf.constant(np.array([3.,7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [20]:
#convert our tensor back to a numpy array.

print(np.array(J))
print(type(np.array(J)))


[ 3.  7. 10.]
<class 'numpy.ndarray'>


In [21]:
J.numpy()

array([ 3.,  7., 10.])

In [23]:
type(J.numpy())

numpy.ndarray

In [25]:
data = tf.constant([3.])
print(data)
print(data.numpy())
print(data.numpy()[0])

tf.Tensor([3.], shape=(1,), dtype=float32)
[3.]
3.0


In [26]:
#Default type of tensorflow and numpy are slighlty different.

numpy_J = tf.constant(np.array([3.,4.,5.]))
tensor_J = tf.constant([3.,7.,10.])
print(numpy_J)
print(tensor_J)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float64)
tf.Tensor([ 3.  7. 10.], shape=(3,), dtype=float32)


In [28]:
print(numpy_J.dtype)
print(tensor_J.dtype)

<dtype: 'float64'>
<dtype: 'float32'>


In [29]:
#Finding access to  GPU

import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

To acess GPU on google colab.

click on runtime

click on change runtime type

select GPU

save.

In [30]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [31]:
!nvidia-smi

Mon Jan 10 14:51:22 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P0    70W / 149W |    147MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Note: If you have acess to a CUDA enabled GPU, tensorflow will automatically use it whenever posiible. Google colab have it. 