In [2]:
import tensorflow as tf

In [3]:
# In machine learning, matrix multiplication is one of the most common operation.
#matrix multiplication in tensorflow.

tensor = tf.constant([[1,2], [3,4]])
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [5]:
#matrix multiplication with python operator. "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [6]:
# create two tensors wof same shape (3,2)

x = tf.constant([[1,2], [3,4], [5,6]])
y = tf.constant([[7,8],[9,10],[11,12]])
print(x)
print(y)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [7]:
tf.matmul(x,y)

InvalidArgumentError: ignored

In [8]:
#In above cell we can see the error because the inner dimension of both the
#tensor doesnot match. To match the inner dimension we can repsahpe one of the
#tensor or we can transpose one of the tensor. Let's try both.

In [9]:
tf.reshape(y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [10]:
x @ tf.reshape(y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [11]:
tf.matmul(x, tf.reshape(y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [12]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [13]:
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [14]:
tf.transpose(x) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

The dot product:

Matrix multiplication is also reffered to as the dot product.

You can perform matrix multiplication using:

tf.matmul()

tf.tensordot()

@

In [15]:
#perform the dot product on x and y (required x or y) to be transposed.
print(x)
print(y)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [16]:
tf.tensordot(tf.transpose(x), y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [17]:
#perform matrix multiplication b/w x and y(transposed).

tf.tensordot(x, tf.transpose(y), axes  = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [18]:
#perform matrix multiplication b/w x and y(reshaped)

tf.matmul(x , tf.reshape(y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [19]:
#check the value of y, reshape y and transposed Y.

print('normal y:')
print(y, '\n')

print('reshape y:')
print(tf.reshape(y, shape=(2,3)), '\n')

print('transposed y:')
print(tf.transpose(y))

normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

reshape y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

transposed y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Note: Generally during performing matrix multiplication on two tensors and one of the tensor axes dosent line up, you will transpose (rather then reshape) one of the tenors to get satisfying the matrix multiplication rules.