In [1]:
import tensorflow as tf

In [2]:
#create vector, scalar, matrix and tensor with values of your choosing using tf.constant()

vector = tf.constant(1)
scalar = tf.constant([1,2,3])
matrix = tf.constant([[1,2],
                      [3,4]])

In [3]:
print(vector)
print(scalar)
print(matrix)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
#Find the shape, rank and size of the tensors you created in 1.

print(vector.shape, vector.ndim, tf.size(vector))
print(scalar.shape, scalar.ndim, tf.size(scalar))
print(matrix.shape, matrix.ndim, tf.size(matrix))

() 0 tf.Tensor(1, shape=(), dtype=int32)
(3,) 1 tf.Tensor(3, shape=(), dtype=int32)
(2, 2) 2 tf.Tensor(4, shape=(), dtype=int32)


In [18]:
#Create two tensors containing random values between 0 and 1 with shape [5,300].

tf.random.set_seed(42)
random1 = tf.random.uniform(shape = [5,300], minval = 0, maxval=1)
print(random1, '\n')
random2 = tf.random.uniform(shape = [5,300], minval = 0, maxval = 1)
print(random2)

tf.Tensor(
[[0.6645621  0.44100678 0.3528825  ... 0.31410468 0.7593535  0.03699052]
 [0.532024   0.29129946 0.10571766 ... 0.54052293 0.31425726 0.2200619 ]
 [0.08404207 0.03614604 0.97732127 ... 0.21516645 0.9786098  0.00726748]
 [0.7396945  0.6653172  0.0787828  ... 0.7117733  0.07013571 0.9409125 ]
 [0.15861344 0.12024033 0.27218235 ... 0.8824879  0.1432488  0.44135118]], shape=(5, 300), dtype=float32) 

tf.Tensor(
[[0.68789124 0.48447883 0.9309944  ... 0.6920762  0.33180213 0.9212563 ]
 [0.27369928 0.10631859 0.6218617  ... 0.4382149  0.30427706 0.51477313]
 [0.00920248 0.37280262 0.8177401  ... 0.56786287 0.49201214 0.9892651 ]
 [0.88608265 0.08672249 0.12160683 ... 0.91770685 0.72545695 0.8280058 ]
 [0.36690474 0.9200133  0.9646884  ... 0.69012    0.7137332  0.2584542 ]], shape=(5, 300), dtype=float32)


In [19]:
#Multiply the two tensors you created in 3 using matrix multiplication.

mat_mul = tf.matmul(random1, tf.transpose(random2))
print(mat_mul)

tf.Tensor(
[[80.33344  73.40498  77.15962  73.98368  80.90053 ]
 [75.146355 68.80437  74.24302  71.841835 75.60206 ]
 [79.7594   75.644554 77.797585 74.74873  80.559845]
 [75.085266 69.06406  74.307755 72.27616  76.05668 ]
 [85.056885 74.266266 78.00687  74.88678  83.13418 ]], shape=(5, 5), dtype=float32)


In [23]:
#Multiply the two tensors you created in 3 using dot product.

dot_pro = tf.tensordot(random1, tf.reshape(random2, shape = (300,5)), axes = 1)
print(dot_pro)

tf.Tensor(
[[76.27581  79.17824  77.82306  79.38919  79.37956 ]
 [72.70634  73.675156 73.71575  74.184204 73.72947 ]
 [75.74081  76.490845 74.435486 78.802124 77.70212 ]
 [68.98616  75.53636  74.5801   76.19232  75.25122 ]
 [75.56366  81.79859  78.68144  80.15668  80.48313 ]], shape=(5, 5), dtype=float32)


In [30]:
#Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

tf.random.set_seed(42)
random_tensor = tf.random.uniform(shape = [224, 224, 3], minval = 0, maxval = 1)

In [32]:
#Find the min and max values of the tensor you created in 6 along the first axis.

tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999998>

In [33]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>

In [38]:
#Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

tensor = tf.constant(tf.random.uniform(shape = [150528]), shape = (1, 224, 224, 3))

In [39]:
tf.squeeze(tensor)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95831835, 0.01680839, 0.3156035 ],
        [0.16013157, 0.7148702 , 0.7892921 ],
        [0.11484027, 0.33310425, 0.21091413],
        ...,
        [0.6279857 , 0.85051286, 0.9490392 ],
        [0.62438786, 0.2802421 , 0.18754554],
        [0.9087832 , 0.46846092, 0.5317346 ]],

       [[0.85744655, 0.51288927, 0.18603599],
        [0.04882693, 0.78045344, 0.79377043],
        [0.9356363 , 0.32798207, 0.15949786],
        ...,
        [0.6933085 , 0.5420611 , 0.1860913 ],
        [0.7326596 , 0.9234495 , 0.07200372],
        [0.5471792 , 0.24985266, 0.14673471]],

       [[0.5033684 , 0.7000841 , 0.21468806],
        [0.9304948 , 0.17212296, 0.720364  ],
        [0.6657183 , 0.17304075, 0.7110392 ],
        ...,
        [0.35423398, 0.126225  , 0.24436975],
        [0.096439  , 0.06387579, 0.32836854],
        [0.15067935, 0.6084572 , 0.47766674]],

       ...,

       [[0.23573959, 0.42224514, 0.9151635 ],
        [0.38

In [62]:
#Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
list1 = [1,2,3,4,5,6,7,8,9]
list1_tesnor = tf.constant(list1)
list1_tesnor.dtype

tf.random.set_seed(42)
tensor = tf.random.uniform(shape = [10])
tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
      dtype=float32)>

In [64]:
tf.argmax(list1_tesnor)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [65]:
list1_tesnor[tf.argmax(list1_tesnor)]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [66]:
#One-hot encode the tensor you created in 9.

tf.one_hot(tf.cast(tensor, dtype = 'int32'), depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [67]:
tf.one_hot(list1_tesnor, depth = 10)

<tf.Tensor: shape=(9, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>