In [1]:
#importing tensorflow

import tensorflow as tf
print(tf.__version__)

2.7.0


What is tensor?

Tensor is the numerical way of representing information or data.

Tensorflow is the open source software library for Machine Learning and Artificial Intelligence. 


In [3]:
#Creating tensor with tf.constant 

Scalar = tf.constant(1)
print(Scalar)
print(Scalar.ndim)

tf.Tensor(1, shape=(), dtype=int32)
0


A single number is called scalar. 

In [9]:
vector = tf.constant([1,2])
print(vector)
print(vector.ndim)

tf.Tensor([1 2], shape=(2,), dtype=int32)
1


Vector is the number with a direction.

In [10]:
matrix = tf.constant([[1,2],
                      [3,4]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
2


A 2 dimensional array of number is called matrix.

In [12]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [1,2,3]]])
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]], shape=(2, 2, 3), dtype=int32)
3


In [13]:
tensor1 = tf.constant([[[1,2,3],
                       [4,5,6],
                      [7,8,9]],
                      [[7,8,9],
                       [1,2,3],
                       [4,5,6]]])
print(tensor1)
print(tensor1.ndim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[7 8 9]
  [1 2 3]
  [4 5 6]]], shape=(2, 3, 3), dtype=int32)
3


Tensor is a n dimensional array.

"A 0 dim. tensor is a scalar."

"A 1 dim. tensor is a vector."

"A 2 dim. tensor is a matrix."


Variable tensor:

A variable tensor is a changeable tensor. 

In [16]:
changeable_tensor = tf.Variable([1,2,3])
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [17]:
changeable_tensor[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 2, 3], dtype=int32)>

In [18]:
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 2, 3], dtype=int32)>


In [21]:
changeable_tensor[-1].assign(6)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 2, 6], dtype=int32)>

In [22]:
#creating random tensors.

#Ramdom tensors are tensors of some arbitary size which contain ramdom numbers

In [23]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
print(random1)
print(random1.ndim)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
2


In [24]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3,2))
print(random2)
print(random2.ndim)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
2


In [25]:
random1 ==  random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [26]:
#Shuffling the tensor.

#This is importnat when you want to shuffle your data so tha the inherinet order dosenot effect learning.

In [37]:
not_shuffled = tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9]])
print(not_shuffled, not_shuffled.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 2


In [39]:
shuffle = tf.random.shuffle(not_shuffled)
print(shuffle)

tf.Tensor(
[[7 8 9]
 [1 2 3]
 [4 5 6]], shape=(3, 3), dtype=int32)


In [34]:
#If we want to keep our tensor into same order , we need to use global level ranadom seed as well as operational level random seed.

In [40]:
tf.random.set_seed(42) #Global level random seed.

shuffle = tf.random.shuffle(not_shuffled, seed = 42) #Seed in this is operational level random seed.

In [45]:
print(shuffle)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [46]:
#creating tensors of all ones

ones = tf.ones([10,7])
ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [47]:
#creating tensors of all zeros

zeros = tf.zeros(shape = (3,4))
zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [48]:
#CONVERT numpy arrays into tensors.

# The main difference between numpy arrays and tensor flow tensors is that
# tensors can be run on gpu which is much faster then numperical computing.

In [49]:
import numpy as np
numpy_A = np.arange(1, 25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [52]:
a = tf.constant(numpy_A)
print(a)
print(a.ndim)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int64)
1


In [54]:
#Getting information from the tensor. 

#creating a rank 4 tensor

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [55]:
#Getting various attributes of our tensor. 

print("data type of every element:",  rank_4_tensor.dtype)

data type of every element: <dtype: 'float32'>


In [56]:
print("no. of dimension(rank):", rank_4_tensor.ndim)

no. of dimension(rank): 4


In [57]:
print("shape of tensor:", rank_4_tensor.shape)

shape of tensor: (2, 3, 4, 5)


In [58]:
print("element along 0 axis:", rank_4_tensor.shape[0])

element along 0 axis: 2


In [59]:
print("element along last axis:", rank_4_tensor.shape[-1])

element along last axis: 5


In [60]:
print("total no. of element in our tensor:", tf.size(rank_4_tensor))

total no. of element in our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [61]:
print("total no. of element in our tensor:", tf.size(rank_4_tensor).numpy())

total no. of element in our tensor: 120
